name: build

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  workflow_dispatch
    
env:
  ROM_URL: https://download-cdn.cjjd19.com/123-506/c0964a01/1819490019-0/c0964a01ec20a184465724924101b9fa/c-m71?v=1&t=1755945158&s=295d09f937cf4c539dde37ea5bdd56ad&bzc=1&bzs=1820913880&bzp=0&bi=177253472&filename=Color+OS+13.25.02.23+OPPO+Find+X5.zip&x-mf-biz-cid=c401381d-4254-4597-af79-4538385f8ef0-47df1e&ndcp=1&cache_type=1
  ROM_NAME: ColorOS
  BUILD_TYPE: ab
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
     
       - name: 修复pycrypto编译环境
         run: |
            sudo apt-get update
            sudo apt-get install -y python3-dev libssl-dev zlib1g-dev
            pip uninstall -y pycrypto
            pip install pycryptodome
     
       - name: 修复 Python 头文件问题
         run: |
            sudo apt-get install -y python3-dev python3-venv
            python3 -m venv .venv
            source .venv/bin/activate
            pip uninstall -y pycrypto
            pip install pycryptodome
           
       - name: 解决 Python 3.12 头文件冲突
         run: |
            sudo apt-get install -y python3.10-dev libssl-dev zlib1g-dev
            python3.10 -m venv .venv
            source .venv/bin/activate
            pip uninstall -y pycrypto
            pip install --no-cache-dir pycryptodome

       - name: Checkout
         uses: actions/checkout@master

       - name: Cleanup
         uses: rokibhasansagar/slimhub_actions@main
           
       - name: Initialization environment
         run: |
            sudo apt install git wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/mi20210630/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              mkdir ./output
              sudo bash ./setup.sh
              
       - name: Download Stock Rom & Generate GSI
         run: |
             cd $GITHUB_WORKSPACE/ErfanGSIs
             sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              touch info.txt
              echo "By mi20210630 developed action" >>info.txt
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              mkdir upload
              zip -r GSI.zip ./*
              if [[ $(du -sb "GSI.zip" | awk '{print $1}') -gt 2097152000 ]];then
                  echo -e "split packaging..."
                  tar -cpzf - "GSI.zip" | split -d -b 1024m - "upload/GSI.zip"
              else
                  mv GSI.zip upload/
              fi
              ls "upload"                  
              
       - name: Upload GSI to release
         uses: ncipollo/release-action@v1.8.6
         with:
           artifacts: ${{ github.workspace }}/ErfanGSIs/output/upload/*
           tag: ErfanGSIs-${{ env.ROM_NAME }}-${{ env.BUILD_TYPE }}-${{ github.run_number }}
           bodyFile: "info.txt"
           token: ${{ secrets.GITHUB_TOKEN }}
